title: Manny Brar # your name (or website title) here
logo: "/images/profilepic.jpg?raw=false" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  For the last 4 years, I have been studying 
  and working within the field of big data analytics,
  data science, statistics, and distributed systems.
  This is something I am genuinely passionate
  and excited about. I am a very analytical individual 
  and genuinely enjoy exploring and making 
  sense of data and finding new and innovative
  ways to utilize data. 
  <br><br>
  
  
 
  <a href="https://www.linkedin.com/in/manny-brar-analytics/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
