title: Manny Brar # your name (or website title) here
logo: "/images/profilepic.jpg?raw=false" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br>
  
  
 
  <a href="https://www.linkedin.com/in/manny-brar-analytics/">LinkedIn</a> 
  
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
