title: Manny Brar # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
 
 With all the negativity in news headlines recently, it can be a real strain on mental health when you are constantly bombarded with negative news articles and headlines. This project was intended to assist, when you just need a break from negative news articles and want to filter news by positive, neutral or negative sentiment. This was the problem I wanted to create a solution for and by developing a pipeline that performs real-time sentiment analysis on news articles and allows for the user to filter results based on positive or negative sentiment of each article
 
 ---
  <a href="https://www.linkedin.com/in/manny-brar-analytics/">LinkedIn</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
